### PR TITLE
VVenC-based encoding with experimental muxing via NUT format

### PR DESCRIPTION
**Pull request by IsaMorphic**
Was working on this for myself but decided I wanted to contribute to the "og" fork :)

### CODE REVIEW

**Comment by MartinEesmaa** [comment]
Cool, @yodadude2003! Nice for your vvenc codes very appreciated sir, thank you. I'll test it out...

**Comment by IsaMorphic** [comment]
Thank you! There's one more bug that I think I need to work out, I'm not accounting for the startup delay where the encoder is caching frames at the start when calculating timestamps for packets. This results in duplicated frames when decoding at the start of the file. I'll test this theory and try to fix the bug today!

**Comment by MartinEesmaa** [comment]
@yodadude2003, no problem 👍. It's very good of future video codec.
Anyways, I notice it's only preset medium and qp 32 too, so I cannot change my qp and presets in libvvenc FFmpeg. Don't forget to add presets and qp changeable too of libvvenc , so good luck for you :), I'll update my repository of VVCEasy to add libvvenc FFmpeg.

- Martin Eesmaa

**Comment by IsaMorphic** [comment]
Sounds good @MartinEesmaa!! You can adjust the QP with the global_quality flag at the moment. But I will make sure to include these features in my next commit as formally named parameters!

**Comment by MartinEesmaa** [comment]
Thank you, @yodadude2003 for marking star to my forked repository. Unfortunately I have a lot C errors saying that: field name not in record or union initializer of libvv(enc/dec). If I cannot solve the C errors, I might delete [my forked repository](https://github.com/MartinEesmaa/FFmpegVVC-latest), so you're very good C programmer and might be better do to for this repository. Wish a good luck...

- Martin Eesmaa

**Comment by IsaMorphic** [comment]
No worries! I can't say I'm an expert either. I noticed that the API surface has changed quite a bit for adding new encoders and decoders on the ffmpeg trunk. There are new macros as well. It may be quite a difficult port.

**Pull request closed without merging**
